### ISSUE TITLE
[Documentation] Imprécision sur le fichier `gitlab-ci`

### ISSUE THREAD

**Issue by mgrzybek** [dnum-mi/dso-doc#1]
Dans https://github.com/dnum-mi/dso-doc#synchroniser-les-d%C3%A9p%C3%B4ts on parle de créer un fichier `gitlab-ci`. Ce serait bien de dire explicitement « Créer le fichier `.gitlab-ci.yml` à la racine du dépôt » par exemple.

**Comment by this-is-tobi** [comment]
Fixed in https://github.com/dnum-mi/dso-doc/commit/35cb536ee19a69a5fb0cc960d8e0e7e247ffd291
